### ISSUE TITLE
Custom keyword -> number mapping

### ISSUE THREAD

**Issue by fregante** [jonathantneal/postcss-font-weights#3]
Would you be open to have it accept a custom keyword->number mapping? I'm using a font with two distinct "heavy" and "black" weights, which W3 sets to 900. 

I might be able to send a PR to accept something like:

``` js
postcss([
    require('postcss-font-weights')({
        black: 800,
        heavy: 900
    })
]);
```

To override or extend the [existing mapping](https://www.npmjs.com/package/css-font-weight-names)

**Comment by jonathantneal** [comment]
This is fulfilled by the https://github.com/jonathantneal/postcss-font-weights#custom option, yea @bfred-it ?
